config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tutuer/index'
  root 'searches#show'
  resources :tickets
  resource :search, only: [:show, :create]

  namespace :admin do
    resources :trains do
      resources :wagons, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrive, on: :member
      patch :update_departure, on: :member
    end
    resources :routes
    resources :users
    resources :tickets
    resources :panels, only: [:index]
  end

  get 'railway_stations/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comfort.rb
class Comfort < Wagon
  validates :lower_places, presence: true
end

app/models/coupe.rb
class Coupe < Wagon
  validates :upper_places, :lower_places, presence: true
end

app/models/platzkart.rb
class Platzkart < Wagon
  validates :upper_places, :lower_places, :side_upper_places, :side_lower_places, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains
  has_many :tickets, through: :railway_stations_tickets
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  validates :title, presence: true

  scope :ordered, -> { joins(:railway_stations_routes)
                           .order("railway_stations_routes.position")
                           .distinct }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  def update_arrive(route, arrive)
    station_route = station_route(route)
    station_route.update(arrive: arrive) if station_route
  end

  def update_departure(route, departure)
    station_route = station_route(route)
    station_route.update(departure: departure) if station_route
  end

  def arrive_at(route)
    station_route(route).try(:arrive)
  end

  def departure_at(route)
    station_route(route).try(:departure)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ActiveRecord::Base
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: {scope: :route_id }

  scope :sorted, -> { order(:station_position) }
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true

  scope :routes_for, ->(station_kind) {
    joins(:railway_stations)
        .where(railway_stations: { id: station_kind })
  }
end

app/models/search.rb
class Search

  def self.get_trains(start_station, end_station)
    unless start_station == end_station
      routes = Route.routes_for(start_station) & Route.routes_for(end_station)
      Train.joins(:route).where(route: routes)
    end
  end

end

app/models/sitting.rb
class Sitting < Wagon
  validates :seats, presence: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :train
  belongs_to :source, class_name: 'RailwayStation', foreign_key: :source_id
  belongs_to :destination, class_name: 'RailwayStation', foreign_key: :destination_id

  after_create :send_buy_notificatiom
  after_destroy :send_drop_notification

  def route_name
    "#{source.title} - #{destination.title}"
  end

  private

  def send_buy_notificatiom
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def send_drop_notification
    TicketsMailer.drop_ticket(self.user, self).deliver_now
  end
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :wagons

  validates :number, presence: true

  def places(wagon_type, place_type)
    self.wagons.where(type:wagon_type).sum(place_type)
  end

  def sorted
    head_sort ? wagons.sorted_fwd : wagons.sorted_back
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :tickets


end

app/models/wagon.rb
class Wagon < ApplicationRecord
  belongs_to :train

  validates :number, uniqueness: { scope: :train_id }, presence: true

  before_save :assign_number

  scope :sorted_fwd, -> { order(number: :asc) }
  scope :sorted_back, -> { order(number: :desc) }
  scope :wagon_kind, ->(kind) { where(type: kind) }

  def assign_number
    self.number ||= train.wagons.maximum(:number).to_i + 1
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to admin_routes_path, notice: 'Маршрут создан.'
    else
      render :new
    end
  end

  def update
    if @route.update(route_params)
      redirect_to admin_routes_path, notice: 'Маршрут обновлен.'
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path, notice: 'Маршрут удален.'
  end

  private
  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def edit
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      redirect_to @ticket, notice: 'Билет приобретен.'
    else
      render :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: 'Билет изменен.'
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: 'Билет аннулирован.'
  end

  private
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:source_id, :destination_id, :train_id, :passenger_fio, :passport_data)
  end
end

app/controllers/tutuer_controller.rb
class TutuerController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/tutuer_helper.rb
module TutuerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/routes/_form.html.erb
<%= form_for [:admin, route], html: { style: "display: #{hidden ? 'none' : 'block' }"} do |f| %>
    <%= render 'common/errors', resource: route %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :railway_station_ids, t('activerecord.models.railway_station') %>
      <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, multiple: true %>
    </div>

    <div class="actions">
      <%= f.submit "#{route.new_record? ? t('common.create') : t('common.update')}" %>
    </div>
<% end %>

app/views/admin/routes/_route.html.erb
<tr>
  <td>
    <div id="route_name_<%= route.id %>">
      <%= route.name %>
    </div>
    <%= render 'form', route: route, hidden: true %>
  </td>
  <td><%= link_to t('common.show'), [:admin, route] %></td>
  <td><%= link_to t('common.edit'), '', class: 'edit_route', data: { route_id: route.id } %></td>
  <td><%= link_to t('common.delete'), [:admin, route], method: :delete, data: { confirm: t('common.confirm') } %></td>
</tr>

app/views/admin/routes/edit.html.erb
<h1><%= t('common.edit') %></h1>

<%= render 'form', route: @route %>

<%= link_to t('common.back'), admin_routes_path %>

app/views/admin/routes/index.html.erb
<h1><%= t('.routes') %></h1>

<table class="table table-striped" >
  <thead>
    <tr>
      <th><%= t('.name') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <%= render @routes %>
  </tbody>
</table>

<br>

<%= link_to t('admin.routes.new.name'), new_admin_route_path %>
<div></div>
<%= link_to t('admin.panels.index'), admin_panels_path %>

app/views/admin/routes/new.html.erb
<h1><%= t('admin.routes.new.name') %></h1>

<%= render 'form', route: @route %>

<%= link_to t('common.back'), admin_routes_path %>

app/views/admin/routes/show.html.erb
<p>
  <strong><%= t('admin.routes.show.name') %>:</strong>
  <%= @route.name %>
</p>

<p>
<table>
  <tbody>
  <tr>
    <td><%= t('admin.routes.show.route_trains') %></td>
  </tr>
  <% if @route.trains.empty? %>
      <tr>
        <td><%= t('admin.routes.show.no_trains') %></td>
      </tr>
  <% else %>
      <% @route.trains.each do |train| %>
          <tr>
            <td><%= train.number %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>
</p>

<p>
  <strong><%= t('admin.railway_stations.index.railway_stations') %>:</strong>
  <% if @route.railway_stations.empty? %>
      <%= t('admin.routes.show.no_stations') %>
  <% else %>
    <table>
      <thead>
      <tr>
        <td width="150px"><%= t('admin.railway_stations.show.title') %></td>
        <td><%= t('admin.routes.show.position') %></td>
        <td><%= t('admin.routes.show.arrival') %></td>
        <td><%= t('admin.routes.show.departure') %></td>
      </tr>
      </thead>
      <tbody>
      <% @route.railway_stations.ordered.each do |station| %>
          <tr>
            <td><%= station.title %> </td>
            <td>
              <%= form_tag update_position_admin_railway_station_path(station), method: :patch do %>
                  <%= number_field_tag :position, station.position_in(@route) %>
                  <%= hidden_field_tag :route_id, @route.id %>
                  <%= submit_tag t('common.change') %>
              <% end %>
            </td>

            <td>
              <%= form_tag update_arrive_admin_railway_station_path(station), method: :patch do %>
                  <%= datetime_field_tag :arrive, station.arrive_at(@route).strftime("%H:%M") %>
                  <%= hidden_field_tag :route_id, @route.id %>
                  <%= submit_tag t('common.change') %>
              <% end %>
            </td>

            <td>
              <%= form_tag update_departure_admin_railway_station_path(station), method: :patch do %>
                  <%= datetime_field_tag :departure, station.departure_at(@route).strftime("%H:%M") %>
                  <%= hidden_field_tag :route_id, @route.id %>
                  <%= submit_tag t('common.change') %>
              <% end %>
            </td>
          </tr>

      <% end %>
<% end %>
</tbody>
</table>

</p>


<%= link_to t('common.edit'), edit_admin_route_path(@route) %>
<div></div>
<%= link_to t('common.back'), admin_routes_path %>