config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tutuer/index'
  root 'searches#show'
  resources :tickets
  resource :search, only: [:show, :create]

  namespace :admin do
    resources :trains do
      resources :wagons, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrive, on: :member
      patch :update_departure, on: :member
    end
    resources :routes
    resources :users
    resources :tickets
    resources :panels, only: [:index]
  end

  get 'railway_stations/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comfort.rb
class Comfort < Wagon
  validates :lower_places, presence: true
end

app/models/coupe.rb
class Coupe < Wagon
  validates :upper_places, :lower_places, presence: true
end

app/models/platzkart.rb
class Platzkart < Wagon
  validates :upper_places, :lower_places, :side_upper_places, :side_lower_places, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains
  has_many :tickets, through: :railway_stations_tickets
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  validates :title, presence: true

  scope :ordered, -> { joins(:railway_stations_routes)
                           .order("railway_stations_routes.position")
                           .distinct }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  def update_arrive(route, arrive)
    station_route = station_route(route)
    station_route.update(arrive: arrive) if station_route
  end

  def update_departure(route, departure)
    station_route = station_route(route)
    station_route.update(departure: departure) if station_route
  end

  def arrive_at(route)
    station_route(route).try(:arrive)
  end

  def departure_at(route)
    station_route(route).try(:departure)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ActiveRecord::Base
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: {scope: :route_id }

  scope :sorted, -> { order(:station_position) }
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true

  scope :routes_for, ->(station_kind) {
    joins(:railway_stations)
        .where(railway_stations: { id: station_kind })
  }
end

app/models/search.rb
class Search

  def self.get_trains(start_station, end_station)
    unless start_station == end_station
      routes = Route.routes_for(start_station) & Route.routes_for(end_station)
      Train.joins(:route).where(route: routes)
    end
  end

end

app/models/sitting.rb
class Sitting < Wagon
  validates :seats, presence: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :train
  belongs_to :source, class_name: 'RailwayStation', foreign_key: :source_id
  belongs_to :destination, class_name: 'RailwayStation', foreign_key: :destination_id

  after_create :send_buy_notificatiom
  after_destroy :send_drop_notification

  def route_name
    "#{source.title} - #{destination.title}"
  end

  private

  def send_buy_notificatiom
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def send_drop_notification
    TicketsMailer.drop_ticket(self.user, self).deliver_now
  end
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :wagons

  validates :number, presence: true

  def places(wagon_type, place_type)
    self.wagons.where(type:wagon_type).sum(place_type)
  end

  def sorted
    head_sort ? wagons.sorted_fwd : wagons.sorted_back
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :tickets


end

app/models/wagon.rb
class Wagon < ApplicationRecord
  belongs_to :train

  validates :number, uniqueness: { scope: :train_id }, presence: true

  before_save :assign_number

  scope :sorted_fwd, -> { order(number: :asc) }
  scope :sorted_back, -> { order(number: :desc) }
  scope :wagon_kind, ->(kind) { where(type: kind) }

  def assign_number
    self.number ||= train.wagons.maximum(:number).to_i + 1
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      redirect_to [:admin, @ticket], notice: 'Билет приобретен.'
    else
      render :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to [:admin, @ticket], notice: 'Билет изменен.'
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to admin_tickets_url, notice: 'Билет аннулирован.'
  end

  private
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:source_id,
                                   :destination_id,
                                   :train_id,
                                   :passenger_fio,
                                   :passport_data,
                                   :user_id)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def show
  end

  def create
    @trains = Search.get_trains(search_params[:start_station_id], search_params[:end_station_id])
    @start_station = RailwayStation.find(search_params[:start_station_id])
    @end_station = RailwayStation.find(search_params[:end_station_id])
    @set_new_ticket_url = if user_signed_in? && current_user.admin?
      new_admin_ticket_url
    else
      new_ticket_url
    end
    render :show
  end

  private

  def search_params
    params.require(:railway_stations).permit(:start_station_id, :end_station_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def edit
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      redirect_to @ticket, notice: 'Билет приобретен.'
    else
      render :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: 'Билет изменен.'
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: 'Билет аннулирован.'
  end

  private
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:source_id, :destination_id, :train_id, :passenger_fio, :passport_data)
  end
end

app/controllers/tutuer_controller.rb
class TutuerController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/tutuer_helper.rb
module TutuerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/tickets/_form.html.erb
<%= form_for [:admin, @ticket] do |f| %>
    <%= render 'common/errors', resource: @ticket %>

    <div class="field">
      <%= f.label :user_id %>
      <%= f.collection_select :user_id, User.all, :id, :email %>
    </div>

    Поезд №: <%= params[:train_id] %>
    <div></div>
    <%= params[:source_id] %> - <%= params[:destination_id] %>
    <p></p>


    <div class="field">
      <%= f.label :passenger_fio %>
      <%= f.text_field :passenger_fio %>
    </div>
    <div class="field">
      <%= f.label :passport_data %>
      <%= f.text_field :passport_data %>
    </div>

    <%= f.hidden_field :train_id, value: params[:train_id] %>
    <%= f.hidden_field :source_id, value: params[:source_id] %>
    <%= f.hidden_field :destination_id, value: params[:destination_id] %>

    <div class="actions">
      <%= f.submit "#{@ticket.new_record? ? :buy : :edit}" %>
    </div>
<% end %>

app/views/admin/tickets/_ticket.html.erb
<tr>
  <td><%= ticket.train.number %></td>
  <td><%= ticket.source.title %></td>
  <td><%= ticket.destination.title %></td>
  <td><%= ticket.passenger_fio %></td>
  <td><%= ticket.passport_data %></td>
  <td><%= ticket.user.email %></td>
  <td><%= link_to 'Показать', ticket %></td>
  <td><%= link_to 'Редактировать', edit_ticket_path(ticket) %></td>
  <td><%= link_to 'Удалить', ticket, method: :delete, data: {confirm: 'Вы уверены?'} %></td>
</tr>

app/views/admin/tickets/edit.html.erb
<h1>Редактирование билета</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Назад', tickets_path %>

app/views/admin/tickets/index.html.erb
<h1>Билеты</h1>

<table class="table table-striped" >
  <thead>
  <tr>
    <td>Поезд №</td>
    <td>Станция отправления</td>
    <td>Станция прибытия</td>
    <td>ФИО пассажира</td>
    <td>Паспорт</td>
    <td>Покупатель билета</td>
  </tr>
  </thead>
  <tbody>
  <% if @tickets.empty? %>
      <tr>
        <td>Приобретенных билетов нет</td>
      </tr>
  <% else %>
      <% @tickets = current_user.tickets unless current_user.admin? %>
      <%= render @tickets %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый билет', search_path %>
<div></div>
<%= link_to 'Главное меню', admin_panels_path %>

app/views/admin/tickets/new.html.erb
<h1>Новый билет</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Назад', tickets_path %>

app/views/admin/tickets/show.html.erb
Поезд №: <%= @ticket.train.number %>
  <div></div>
<%= @ticket.source.title %> - <%= @ticket.destination.title %>
<div></div>
ФИО пассажира: <%= @ticket.passenger_fio %>
<div></div>
Паспорт: <%= @ticket.passport_data %>
<p></p>

<%= link_to 'Редактировать', edit_admin_ticket_path(@ticket) %> |
<%= link_to 'Назад', admin_tickets_path %>