config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tutuer/index'
  root 'searches#show'
  resources :tickets
  resource :search, only: [:show, :create]

  namespace :admin do
    resources :trains do
      resources :wagons, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrive, on: :member
      patch :update_departure, on: :member
    end
    resources :routes
    resources :users
    resources :tickets
    resources :panels, only: [:index]
  end

  get 'railway_stations/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comfort.rb
class Comfort < Wagon
  validates :lower_places, presence: true
end

app/models/coupe.rb
class Coupe < Wagon
  validates :upper_places, :lower_places, presence: true
end

app/models/platzkart.rb
class Platzkart < Wagon
  validates :upper_places, :lower_places, :side_upper_places, :side_lower_places, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains
  has_many :tickets, through: :railway_stations_tickets
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  validates :title, presence: true

  scope :ordered, -> { joins(:railway_stations_routes)
                           .order("railway_stations_routes.position")
                           .distinct }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  def update_arrive(route, arrive)
    station_route = station_route(route)
    station_route.update(arrive: arrive) if station_route
  end

  def update_departure(route, departure)
    station_route = station_route(route)
    station_route.update(departure: departure) if station_route
  end

  def arrive_at(route)
    station_route(route).try(:arrive)
  end

  def departure_at(route)
    station_route(route).try(:departure)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ActiveRecord::Base
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: {scope: :route_id }

  scope :sorted, -> { order(:station_position) }
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true

  scope :routes_for, ->(station_kind) {
    joins(:railway_stations)
        .where(railway_stations: { id: station_kind })
  }
end

app/models/search.rb
class Search

  def self.get_trains(start_station, end_station)
    unless start_station == end_station
      routes = Route.routes_for(start_station) & Route.routes_for(end_station)
      Train.joins(:route).where(route: routes)
    end
  end

end

app/models/sitting.rb
class Sitting < Wagon
  validates :seats, presence: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :train
  belongs_to :source, class_name: 'RailwayStation', foreign_key: :source_id
  belongs_to :destination, class_name: 'RailwayStation', foreign_key: :destination_id

  after_create :send_buy_notificatiom
  after_destroy :send_drop_notification

  def route_name
    "#{source.title} - #{destination.title}"
  end

  private

  def send_buy_notificatiom
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def send_drop_notification
    TicketsMailer.drop_ticket(self.user, self).deliver_now
  end
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :wagons

  validates :number, presence: true

  def places(wagon_type, place_type)
    self.wagons.where(type:wagon_type).sum(place_type)
  end

  def sorted
    head_sort ? wagons.sorted_fwd : wagons.sorted_back
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :tickets


end

app/models/wagon.rb
class Wagon < ApplicationRecord
  belongs_to :train

  validates :number, uniqueness: { scope: :train_id }, presence: true

  before_save :assign_number

  scope :sorted_fwd, -> { order(number: :asc) }
  scope :sorted_back, -> { order(number: :desc) }
  scope :wagon_kind, ->(kind) { where(type: kind) }

  def assign_number
    self.number ||= train.wagons.maximum(:number).to_i + 1
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to admin_trains_path, notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    if @train.update(train_params)
      redirect_to admin_trains_path, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    redirect_to admin_trains_path, notice: 'Train was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
    def train_params
      params.require(:train).permit(:number,
                                    :current_station_id,
                                    :route_id,
                                    :head_sort)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def show
  end

  def create
    @trains = Search.get_trains(search_params[:start_station_id], search_params[:end_station_id])
    @start_station = RailwayStation.find(search_params[:start_station_id])
    @end_station = RailwayStation.find(search_params[:end_station_id])
    @set_new_ticket_url = if user_signed_in? && current_user.admin?
      new_admin_ticket_url
    else
      new_ticket_url
    end
    render :show
  end

  private

  def search_params
    params.require(:railway_stations).permit(:start_station_id, :end_station_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def edit
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      redirect_to @ticket, notice: 'Билет приобретен.'
    else
      render :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: 'Билет изменен.'
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: 'Билет аннулирован.'
  end

  private
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:source_id, :destination_id, :train_id, :passenger_fio, :passport_data)
  end
end

app/controllers/tutuer_controller.rb
class TutuerController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/tutuer_helper.rb
module TutuerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, train], html: { style: "display: #{hidden ? 'none' : 'block' }"}  do |f| %>
    <%= render 'common/errors', resource: train %>

    <div class="field">
      <%= f.label :number %>
      <%= f.text_field :number %>
    </div>

    <div class="field">
      <%= f.label :route %>
      <%= f.collection_select :route_id, Route.all, :id, :name %>
    </div>

    <div class="field">
      <%= f.label :current_station %>
      <%= f.collection_select :current_station_id, RailwayStation.all, :id, :title %>
    </div>

    <div class="field">
      <%= f.label t('admin.trains.index.sort_ahead') %>
      <%= f.select :head_sort, [true, false]%>
    </div>

    <div class="actions">
      <%= f.submit "#{train.new_record? ? t('common.create') : t('common.change')}" %>
    </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td>
    <div id="train_number_<%= train.id %>">
      <%= train.number %>
    </div>
    <%= render 'form', train: train, hidden: true %>
  </td>
  <td><%= link_to t('common.show'), [:admin, train] %></td>
  <td><%= link_to t('common.edit'), '', class: 'edit_train', data: { train_id: train.id } %></td>
  <td><%= link_to t('common.delete'), [:admin, train], method: :delete, data: { confirm: t('common.confirm') } %></td>
</tr>

app/views/admin/trains/_wagon.html.erb
<%= link_to wagon.number, wagon_path(wagon.id) %> - <%= wagon.type %>
<div></div>

app/views/admin/trains/edit.html.erb
<h1><%= t('common.edit') %></h1>

<%= render 'form', train: @train, hidden: false %>

<%= link_to t('common.show'), [:admin, @train] %> |
<%= link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/index.html.erb
<h1><%=t('.trains') %></h1>

<table class="table table-striped" >
  <thead>
    <tr>
      <th><%=t('admin.trains.index.number') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to t('admin.trains.new.number'), new_admin_train_path %>
<div></div>
<%= link_to t('admin.panels.index'), admin_panels_path %>

app/views/admin/trains/new.html.erb
<h1><%= t('admin.trains.new.number') %></h1>

<%= render 'form', train: @train, hidden: false %>

<%= link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/show.html.erb
<p>
  <strong><%= t('admin.trains.show.number') %>:</strong>
  <%= @train.number %>
<div></div>
<strong><%= t('activerecord.models.route') %>:</strong>
<% if @train.route %>
    <%= @train.route.name %>
<% else %>
    <%= t('admin.trains.show.no_route') %>
<% end %>
<div></div>

<p>
  <strong><%= t('activerecord.models.wagons') %></strong>
<ul>
  <% @train.wagons.each do |w| %>
      <li><%=  link_to "#{t('activerecord.models.wagon')} #{w.number}, #{w.type}", admin_wagon_url %></li>
  <% end %>

</ul>

<p>
<%= link_to t('admin.trains.show.add_wagon'), new_admin_train_wagon_path(@train) %>
</p>

<%= link_to t('common.edit'), edit_admin_train_path(@train) %> |
<%= link_to t('common.back'), admin_trains_path %>