config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tutuer/index'
  root 'searches#show'
  resources :tickets
  resource :search, only: [:show, :create]

  namespace :admin do
    resources :trains do
      resources :wagons, shallow: true
    end
    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrive, on: :member
      patch :update_departure, on: :member
    end
    resources :routes
    resources :users
    resources :tickets
    resources :panels, only: [:index]
  end

  get 'railway_stations/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comfort.rb
class Comfort < Wagon
  validates :lower_places, presence: true
end

app/models/coupe.rb
class Coupe < Wagon
  validates :upper_places, :lower_places, presence: true
end

app/models/platzkart.rb
class Platzkart < Wagon
  validates :upper_places, :lower_places, :side_upper_places, :side_lower_places, presence: true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains
  has_many :tickets, through: :railway_stations_tickets
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  validates :title, presence: true

  scope :ordered, -> { joins(:railway_stations_routes)
                           .order("railway_stations_routes.position")
                           .distinct }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  def update_arrive(route, arrive)
    station_route = station_route(route)
    station_route.update(arrive: arrive) if station_route
  end

  def update_departure(route, departure)
    station_route = station_route(route)
    station_route.update(departure: departure) if station_route
  end

  def arrive_at(route)
    station_route(route).try(:arrive)
  end

  def departure_at(route)
    station_route(route).try(:departure)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ActiveRecord::Base
  belongs_to :railway_station
  belongs_to :route

  validates :railway_station_id, uniqueness: {scope: :route_id }

  scope :sorted, -> { order(:station_position) }
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true

  scope :routes_for, ->(station_kind) {
    joins(:railway_stations)
        .where(railway_stations: { id: station_kind })
  }
end

app/models/search.rb
class Search

  def self.get_trains(start_station, end_station)
    unless start_station == end_station
      routes = Route.routes_for(start_station) & Route.routes_for(end_station)
      Train.joins(:route).where(route: routes)
    end
  end

end

app/models/sitting.rb
class Sitting < Wagon
  validates :seats, presence: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :train
  belongs_to :source, class_name: 'RailwayStation', foreign_key: :source_id
  belongs_to :destination, class_name: 'RailwayStation', foreign_key: :destination_id

  after_create :send_buy_notificatiom
  after_destroy :send_drop_notification

  def route_name
    "#{source.title} - #{destination.title}"
  end

  private

  def send_buy_notificatiom
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def send_drop_notification
    TicketsMailer.drop_ticket(self.user, self).deliver_now
  end
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :wagons

  validates :number, presence: true

  def places(wagon_type, place_type)
    self.wagons.where(type:wagon_type).sum(place_type)
  end

  def sorted
    head_sort ? wagons.sorted_fwd : wagons.sorted_back
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :tickets


end

app/models/wagon.rb
class Wagon < ApplicationRecord
  belongs_to :train

  validates :number, uniqueness: { scope: :train_id }, presence: true

  before_save :assign_number

  scope :sorted_fwd, -> { order(number: :asc) }
  scope :sorted_back, -> { order(number: :desc) }
  scope :wagon_kind, ->(kind) { where(type: kind) }

  def assign_number
    self.number ||= train.wagons.maximum(:number).to_i + 1
  end
end

app/controllers/admin/wagons_controller.rb
class Admin::WagonsController < Admin::BaseController
  before_action :set_wagon, only: [:show, :edit, :update, :destroy]
  before_action :set_train, only: [:new, :create]

  def index
    @wagons = Wagon.all
  end

  def show
    @wagon = Wagon.find(params[:id])
  end

  def new
    @wagon = Wagon.new
  end

  def edit
  end

  def create
    @wagon = @train.wagons.new(wagon_params)
    if @wagon.save
      redirect_to admin_trains_path, notice: 'Вагон создан.'
    else
      render :new
    end
  end

  def update
    if @wagon.update(wagon_params)
      redirect_to admin_wagons_path, notice: 'Вагон изменен.'
    else
      render :edit
    end
  end

  def destroy
    @wagon.destroy
    redirect_to admin_wagons_path, notice: 'Вагон удален.'
  end

  protected

  def set_train
    @train = Train.find(params[:train_id])
  end

  def set_wagon
    @wagon = Wagon.find(params[:id])
  end

  def wagon_params
    params.require(:wagon).permit(:number,
                                  :upper_places,
                                  :lower_places,
                                  :side_upper_places,
                                  :side_lower_places,
                                  :seats,
                                  :type,
                                  :train_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def edit
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      redirect_to @ticket, notice: 'Билет приобретен.'
    else
      render :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: 'Билет изменен.'
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: 'Билет аннулирован.'
  end

  private
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:source_id, :destination_id, :train_id, :passenger_fio, :passport_data)
  end
end

app/controllers/tutuer_controller.rb
class TutuerController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/tutuer_helper.rb
module TutuerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/wagons/_comfort.html.erb
<div></div>
Нижние :  <%= @wagon.lower_places %>

app/views/admin/wagons/_coupe.html.erb
<div></div>
Верхние : <%= @wagon.upper_places %>
<div></div>
Нижние : <%= @wagon.lower_places %>

app/views/admin/wagons/_form.html.erb
<%= form_for [:admin, @train,   wagon.becomes(Wagon)] do |f| %>
    <%= render 'common/errors', resource: wagon %>

    <div class="field">
      <%= f.label :wagon_type %>
      <%= f.select :type, [' ', 'Coupe', 'Platzkart', 'Comfort', 'Sitting'] %>
    </div>

    <div class="comfort" style="display: <% hidden ? 'none' : 'block'%>">
      <div class="field">
        <%= f.label :lower_places %>
        <%= f.number_field :lower_places %>
      </div>
    </div>

    <div class="coupe" style="display: <% hidden ? 'none' : 'block'%>">
      <div class="field">
        <%= f.label :upper_places %>
        <%= f.number_field :upper_places %>
      </div>

      <div class="field">
        <%= f.label :lower_places %>
        <%= f.number_field :lower_places %>
      </div>
    </div>

    <div class="platzkart" style="display: <% hidden ? 'none' : 'block'%>">
      <div class="field">
        <%= f.label :upper_places %>
        <%= f.number_field :upper_places %>
      </div>

      <div class="field">
        <%= f.label :lower_places %>
        <%= f.number_field :lower_places %>
      </div>

      <div class="field">
        <%= f.label :side_upper_places %>
        <%= f.number_field :side_upper_places %>
      </div>

      <div class="field">
        <%= f.label :side_lower_places %>
        <%= f.number_field :side_lower_places %>
      </div>
    </div>

    <div class="sitting" style="display: <% hidden ? 'none' : 'block'%>">
      <div class="field">
        <%= f.label :seats %>
        <%= f.number_field :seats %>
      </div>
    </div>

    <%= f.hidden_field :train_id, value: @train.id %>

    <div class="actions">
      <%= f.submit "#{wagon.new_record? ? 'Создать' : 'Изменить'}" %>
    </div>
<% end %>

app/views/admin/wagons/_platzkart.html.erb
<div></div>
Верхние : <%= @wagon.upper_places %>
<div></div>
Нижние : <%= @wagon.lower_places %>
<div></div>
Боковые верхние : <%= @wagon.side_upper_places %>
<div></div>
Боковые нижние : <%= @wagon.side_lower_places %>

app/views/admin/wagons/_sitting.html.erb
<div></div>
Сидячие : <%= @wagon.seats %>

app/views/admin/wagons/_wagon.html.erb
<tr>
  <td><%= wagon.number %></td>
  <td><%= wagon.type %></td>
  <td><%= link_to 'Показать', admin_wagon_path(wagon) %></td>
  <td><%= link_to 'Редактировать', edit_admin_wagon_path(wagon) %></td>
  <td><%= link_to 'Удалить', admin_wagon_path(wagon), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/wagons/edit.html.erb
<h1>Редактирование вагона</h1>

<%= render 'form', wagon: @wagon, hidden: true %>

<%= link_to 'Назад', admin_train_wagons_path %>

<div></div>

app/views/admin/wagons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Вагоны</h1>

<table>
  <thead>
  <tr>
    <th>Имя</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render partial: 'admin/wagons/wagon', collection: @wagons %>
  </tbody>
</table>

<br>

<%= link_to 'Новый вагон', new_admin_train_wagon_path %>
<div></div>
<%= link_to 'Главное меню', root_path %>

<div></div>

app/views/admin/wagons/new.html.erb
<h1>Новый вагон</h1>

<%= form_for [:admin, @train, @wagon] do |f|%>
    <div class="field">
      <%= f.label :number %><br>
      <%= f.text_field :number %>
    </div>

    <div class="field">
      <%= f.label :upper_places %><br>
      <%= f.number_field :upper_places %>
    </div>

    <div class="field">
      <%= f.label :lower_places %><br>
      <%= f.number_field :lower_places %>
    </div>

    <div class="field">
      <%= f.label :side_upper_places %><br>
      <%= f.number_field :side_upper_places %>
    </div>

    <div class="field">
      <%= f.label :side_lower_places %><br>
      <%= f.number_field :side_lower_places %>
    </div>

    <div class="actions">
      <%= f.submit 'Создать' %>
    </div>

<% end %>

app/views/admin/wagons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер:</strong>
  <%= @wagon.number %>
<div></div>
<strong>Тип:</strong>
<%= @wagon.type %>
<div></div>
<strong>Места:</strong>
<%= render @wagon.type.underscore %>
</p>

<%= link_to 'Редактировать', edit_admin_wagon_path(@wagon) %> |
<%= link_to 'Назад', admin_train_path %>
<div></div>